### PR TITLE
Merge office-addin-taskpane-sso

### PR DESCRIPTION
**Pull request by millerds**

### CODE REVIEW

**Review by igor-ribeiiro — APPROVED** [review]

**Comment by millerds** [comment]
Mac lint needs to be looked at on a Mac machine.

**Comment by igor-ribeiiro** [comment]
> Mac lint needs to be looked at on a Mac machine.

It doesn't have any feedback on the error?

**Comment by millerds** [comment]
> > Mac lint needs to be looked at on a Mac machine.
> 
> It doesn't have any feedback on the error?

Nope . . . just error code 2 when trying to run 'office-addin-lint check'

**Pull request merged**
